version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aulas_pos
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
